services:
  - type: web
    name: jarvis2-0
    runtime: node
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: read_customers,read_discounts,read_fulfillments,read_orders,read_product_listings,read_products,write_discounts,write_payment_terms,write_products
      - key: HOST
        value: https://jarvis2-0.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: SHOPIFY_CHATBOT_WIDGET_ID
        sync: false
